name: SkyblockReborn
main: me.alwayslg.SkyblockReborn
version: 1.0
commands:
  getitems:
    usage: /<command>
    aliases:
      - gui
  spawnzombie:
    usage: /<command>
  spawnnecron:
    usage: /<command>
  spawngolem:
    usage: /<command>
  ride:
    description: Ride another player
    usage: /ride <player>
  test:
    usage: /<command>
  setpurse:
    usage: /<command> <player> <amount>
  setrank:
    usage: /<command> <player> <rank>
  fly:
    usage: /<command