name: SkyblockReborn
main: me.alwayslg.SkyblockReborn
version: 1.0
commands:
  getitems:
    usage: /<command>
    aliases:
      - gui
  spawnzombie:
    usage: /<command>
  ride:
    description: Ride another player
    usage: /ride <player>